### ISSUE TITLE
Change hash types to [u8; 4]

### ISSUE THREAD

**Issue by rishflab** [Fantom-foundation/lachesis-rs#40]
Currently EventHash and EventSignature are ```Vec<u8>```. ```[u8; 4]``` is more performant and has better type safety.

**Comment by Maxime2** [comment]
EventSignatures are of 64 bytes length, unfortunately traits for fixed size arrays are defined for sizes up to 32, see  https://doc.rust-lang.org/src/core/array.rs.html#259
We either need to implement all traits needed for EventSignature as a fixed array, or leave it as Vec<u8>.

I have changed EventHash  to [u8; 32].
